# Generated by Django 3.0.5 on 2020-06-10 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Mobile Number')),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Pin Code')),
                ('house_number', models.CharField(max_length=90, verbose_name='House Number')),
                ('street', models.CharField(max_length=80, verbose_name='Street')),
                ('Landmark', models.CharField(blank=True, max_length=80, verbose_name='Landmark')),
                ('city', models.CharField(max_length=90, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('preference', models.TextField(verbose_name='Preference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
