# Generated by Django 3.0.5 on 2020-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200620_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_desc_long',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc_short',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='Yes', max_length=3),
            preserve_default=False,
        ),
    ]
