# Generated by Django 3.0.5 on 2020-06-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200623_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_id',
            new_name='cat_id',
        ),
    ]
