# Generated by Django 3.0.5 on 2020-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='pin_code',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='preference',
        ),
        migrations.AddField(
            model_name='address',
            name='housenumber',
            field=models.CharField(blank=True, max_length=90, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='preferences',
            field=models.TextField(default=12, verbose_name='Preference'),
            preserve_default=False,
        ),
    ]
